version: '3.8'
name: blog-client-container
services:
    blog-client: 
        build: .
        image: "blog-client"
        restart: unless-stopped
        ports:
            - '3000:3000'
networks:
    default:
      name: tunnel
      external: true