import {IconDefinition} from "@ant-design/icons-angular";
import {
  BranchesOutline,
  CommentOutline,
  EyeOutline,
  GithubOutline,
  GlobalOutline,
  HeartFill,
  HeartOutline,
  LinkedinOutline,
  LinkOutline,
  MessageOutline,
  ReconciliationOutline,
  ReloadOutline,
  ToolOutline,
  MessageFill,
  LikeTwoTone,
  LikeOutline,
  DislikeTwoTone,
  DislikeOutline,
  DingtalkOutline,
  CrownFill,
  FlagTwoTone,
  StarFill,
  BookTwoTone,
  GiftFill,
  SendOutline,
  PhoneOutline,
  ShoppingFill
} from "@ant-design/icons-angular/icons";

const _icons: IconDefinition[] = [
  GithubOutline,
  LinkedinOutline,
  HeartOutline,
  EyeOutline,
  CommentOutline,
  GlobalOutline,
  ToolOutline,
  ReconciliationOutline,
  LinkOutline,
  BranchesOutline,
  MessageOutline,
  HeartFill,
  ReloadOutline,
  MessageFill,
  LikeTwoTone,
  LikeOutline,
  DislikeTwoTone,
  DislikeOutline,
  DingtalkOutline,
  ShoppingFill,
  CrownFill,
  FlagTwoTone,
  StarFill,
  BookTwoTone,
  GiftFill,
  SendOutline,
  PhoneOutline
];


export const icons = _icons;
